= Post REST API Guide
Always0ne;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response


[[insertPost]]
=== 게시글 작성
`Post` 요청을 사용해서 게시글을 작성 할 수 있다.

operation::insert-post[snippets='http-request,request-fields,http-response,response-fields']

[[getPost]]
=== 게시글 보기
`Post` 요청을 사용해서 게시글을 열람 할 수 있다.

operation::get-post[snippets='http-request,request-fields,http-response,response-fields']

[[updatePost]]
=== 게시글 수정
`Post` 요청을 사용해서 게시글을 수정 할 수 있다.

operation::update-post[snippets='http-request,request-fields,http-response,response-fields']

[[addComment]]
=== 댓글 작성
`Comment` 요청을 사용해서 댓글을 작성 할 수 있다.

operation::add-comment[snippets='http-request,request-fields,http-response,response-fields']

[[getComment]]
=== 댓글 수정
`Comment` 요청을 사용해서 댓글을 열람 할 수 있다.

operation::get-comment[snippets='http-request,request-fields,http-response,response-fields']

[[updateComment]]
=== 댓글 수정
`Comment` 요청을 사용해서 댓글을 수정 할 수 있다.

operation::update-comment[snippets='http-request,request-fields,http-response,response-fields']